### ISSUE TITLE
Issue while redirecting

### ISSUE THREAD

**Issue by bararchy** [icyleaf/halite#11]
It seems Halite had a problem composing the target from this redirect: 

![screenshot at 15-00-57](https://user-images.githubusercontent.com/1631073/31611011-09c9b184-b283-11e7-8e04-4d35bdd6f6f3.png)

Error: 
```
No address found for 172.16.131.135index.php:80 over TCP (Halite::ConnectionError)


```

**Comment by bararchy** [comment]
it took the virtual dir and added it to the host  172.16.131.135index.php:80

**Comment by icyleaf** [comment]
It was fixed. many thanks for using and reporting it.

**Comment by bararchy** [comment]
@icyleaf Working, thanks for quick response :)
