### ISSUE TITLE
Set cookie from session

### ISSUE THREAD

**Issue by bararchy** [icyleaf/halite#12]
Is there a way to tell Halite to automatically update it's own cookie-jar when it get a Set-Cookie header?

```crystal
client.get(URL_WITH_SET_COOKIE) # response cookie 123
client.get(OTHER_URL) # request cookie 123
```

**Comment by icyleaf** [comment]
Please upgrade to the latest and read this: https://github.com/icyleaf/halite#sessions

**Comment by bararchy** [comment]
@icyleaf using head, the issue seems to be in upstream, it seems `HTTP::Cookies.from_headers` (which I guess you use) has issues parsing specific cookie structures

Upstream issue: https://github.com/crystal-lang/crystal/issues/5407
