### ISSUE TITLE
raw output (to String or ...)

### ISSUE THREAD

**Issue by ghost** [icyleaf/halite#15]
Are you funny to implement that the complete response (with headers, 200 OK, ... etc.) is completely copyied to a `String`? I would need this to read all the bytes my server sends, like cookies too and output it myself with `p`, `pp` or simply `puts` :)

I mean, actually we got this via `puts`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
  <!-- ... -->
</body>
</html>
```

and i need this:

```html
HTTP/1.1 200 OK
Date: Mon, 27 Jul 2009 12:28:53 GMT
Server: Apache/2.2.14 (Win32)
Last-Modified: Wed, 22 Jul 2009 19:15:56 GMT
Content-Length: 88
Content-Type: text/html
Connection: Closed

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>
  <!-- ... -->
</body>
</html>
```

prefered as `String` :)

This were nice 👍

**Comment by icyleaf** [comment]
i dont know about this is or not a feature, but for now you can add a patch to your code:

```crystal
class Halite::Response
  def print_debug
    puts "#{version} #{status_code} #{status_message}"
    headers.each do |k, v|
      puts "#{k}: #{v.join(", ")}"
    end
    puts
    puts self
  end
end

url = "https://httpbin.org/get"
r = Halite.get(url)
r.print_debug
```

output:

```
HTTP/1.1 200 OK
Connection: keep-alive
Server: gunicorn/19.8.1
Date: Fri, 22 Jun 2018 03:08:03 GMT
Content-Type: application/json
Content-Length: 200
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Via: 1.1 vegur

{"args":{},"headers":{"Accept":"*/*","Accept-Encoding":"gzip, deflate","Connection":"close","Host":"httpbin.org","User-Agent":"Halite/0.3.2"},"origin":"60.206.194.34","url":"https://httpbin.org/get"}
```

**Comment by icyleaf** [comment]
Or write your [custom logger](https://github.com/icyleaf/halite#use-the-custom-logger) and enable in each request.

**Comment by ghost** [comment]
Wow, you are very fast providing this, thank you 👍 

Firstly, the output seems as expected, but this way its morely a cosmetic output to see this _like_ raw.

This is because of your `puts` - this inserts self-generated newlines after the header key-value-pairs and between headers and body and helps viewing it, but what i exactly mean is the response buffer (chunks chained) directly to String; it should be the real raw response, like

`HTTP/1.1 200 OK\r\nConnection: keep-alive\r\nServer: gunicorn/19.8.1\r\n...`

because sometimes it´s very needed to know whats **exactly** comes in (or _back_) :-)

The custom logger would do the same as it did not catch the original response?

Thank you very much - it´s already a very good starting point :-)

**Comment by icyleaf** [comment]
Let's improve the code 😄 

```crystal
class Halite::Response
  def dump
    String.build do |io|
      io << version << " " << status_code << " " << status_message << "\n"
      headers.each do |k, v|
        io << k << ": " << v.join(", ") << "\n"
      end

      io << "\n"
      io << to_s
    end.to_s
  end
end

url = "https://httpbin.org/get"
r = Halite.get(url)
puts r.dump
```

Is it you want?

**Comment by ghost** [comment]
I do not dare to answer :)

...no... because it´s adding manually `\n` again, and i think `version`, `status_code` and so on are already always parsed Strings.

But i did not dive deep enough into your source; maybe possible that getting this is not possible if Crystals **stdlib** always returns already _parsed strings_. Maybe you got always Strings from their methods and this is the _rawest_ of **raw** :)

If the last one is correct, than you have already saved me a lot of time because i can reduce doing things in the browser to a minimum - thats really awesome 👍  💯

**Comment by icyleaf** [comment]
You are right. all crystal give api is wrapped and it will auto Compression and encoding, check it: https://crystal-lang.org/api/0.25.0/HTTP/Client.html

**Comment by icyleaf** [comment]
BTW, Crystal also give a method to returns raw by splice but Halite not delegate it: https://github.com/crystal-lang/crystal/blob/master/src/http/client/response.cr#L63

**Comment by ghost** [comment]
Wow - thanks!

Ok, so - i am already very happy with your help and Halite - both were awesome for saving time 🥇 

What do you think about merging above to your master? I think, `print_debug` or `dump` are always nice to have 👍 

Let's go with Halite :)

**Comment by icyleaf** [comment]
Done, use `to_raw` to dump it.
