### ISSUE TITLE
Option to send raw post data

### ISSUE THREAD

**Issue by wirrareka** [icyleaf/halite#20]
Hi,

first, thanks for great job on halite! 
I was looking for a way to perform POST request with raw string body, for handling cases that are neither json or form encoded body (handling elasticsearch bulk api in my case). Is that somehow possible ? 

thanks,

Matej

**Comment by icyleaf** [comment]
i will working it. :)

**Comment by icyleaf** [comment]
Use the `master` branch and check the doc: https://github.com/icyleaf/halite/#raw-string

**Comment by wirrareka** [comment]
Works great!
you might want to mention in the docs that with raw mode, the user should set content-type request header manually.

thanks alot!

Matej

**Comment by icyleaf** [comment]
Halite v0.5.0 was released.

Thanks for feedback. welcome for any issues.
