### ISSUE TITLE
Proxy for Web Connection

### ISSUE THREAD

**Issue by prutheus** [icyleaf/halite#48]
Hello.
Coming from Mechanize@Ruby, I want to use Halite@Crystal now.

However, I can't find the possibility to specify a web proxy at Halite::Client for my requests ... Can this be implemented?

**Comment by icyleaf** [comment]
Halite was built on HTTP::Client in Crystal, and current HTTP::Client does not support the ability to use a web proxy, See crystal-lang/crystal#6011 that it was issued for a long long time ago.

BTW, how do you use a web proxy for?

**Comment by icyleaf** [comment]
Sorry, close it with no response for long time, reopen or create new issue anytime please.
