### ISSUE TITLE
0.9.0 was released with 0.8.0 version

### ISSUE THREAD

**Issue by matthewmcgarvey** [icyleaf/halite#60]
not sure if this is an actual issue, just noticed it as I was installing the shard

seeing `Installing halite (0.8.0 at 0.9.0)`

**Comment by icyleaf** [comment]
I forgot to edit the version in `shard.yml`, this tag(release) was correct. 
Thanks to figure is out, i will revoke and release a `v0.9.1` release.

**Comment by icyleaf** [comment]
v0.9.1 was released, it fixed the version name.
