### ISSUE TITLE
Add endpoint as configuration option

### ISSUE THREAD

**Issue by watzon** [icyleaf/halite#64]
It would be nice if we could specify an endpoint when creating a `Halite::Client` instance so that all requests going through that client reference that endpoint.

Something like:

```crystal
cli = Halite::Client.new do |client|
  client.endpoint = "https://api.github.com"
end

response = cli.get("/orgs/octokit/repos")
```

**Comment by icyleaf** [comment]
@watzon I submit a PR to do this issue, Does it solve?

**Comment by watzon** [comment]
@icyleaf looks like it! Thanks :smile:

**Comment by icyleaf** [comment]
Merged and released `v0.10.0`.

**Comment by watzon** [comment]
Thanks!

**Comment by watzon** [comment]
Having a slight problem. When creating a client with 
```crystal
client = Halite::Client.new do
  endpoint "https://api.github.com"
end
```
and then using request
```
client.request(:get, "users/watzon")
```
it's attempting to get `https://api.github.com//users/watzon`. It works if I attempt to get `/users/watzon`, but shouldn't it work without a slash as well?
