### ISSUE TITLE
Endpoint joining is broken

### ISSUE THREAD

**Issue by oprypin** [icyleaf/halite#88]
https://github.com/icyleaf/halite/blob/ba22d2aa96bbb99702145839df8be516b4ceca90/spec/support/mock_server.cr#L46

For endpoint `http://example.com` if I make a request `http://other.example.com/foo`, this will try to request `http://example.com/http://other.example.com/foo`. That's probably not good.

On Windows, what, maybe it'll request `http://example.com\http://other.example.com/foo`??

Pleeease just use [**URI#resolve**](https://crystal-lang.org/api/0.35.1/URI.html#resolve(uri:URI|String):URI-instance-method). Its documentation is very good, so I don't need to explain its merits myself.

**Comment by icyleaf** [comment]
I really do not know `URI#resolve` API before you told me, Thanks.

**Comment by oprypin** [comment]
I don't fully understand what you're saying. Should I explain anything, or help somehow?

**Comment by oprypin** [comment]
Oh I see.
Yes, the API is relatively new.
Thanks

**Comment by icyleaf** [comment]
New version v`0.10.6` is out!
