### ISSUE TITLE
APIError#status_message doesn't actually exist

### ISSUE THREAD

**Issue by oprypin** [icyleaf/halite#90]
There's this documentation and this getter

https://github.com/icyleaf/halite/blob/bac824b15f50683f4d255eeb99de1f1a32fd2695/README.md#L473 https://github.com/icyleaf/halite/blob/d0e8ecad3a983ad3c65d627321fd32593e64292d/src/halite/error.cr#L52

but the variable is never set, so the getter is not usable

```
can't infer the type of instance variable '@status_message' of Halite::Exception::ClientError
```

**Comment by icyleaf** [comment]
You are right, `status_message` is similar as `message` from Exception class, PR is comming.

**Comment by icyleaf** [comment]
Oops, I remembered that this variable was designed as a supplement to the `message` to get more information before and after the requests.

**Comment by icyleaf** [comment]
Fixed
