### ISSUE TITLE
since 0.10.7 halite breaks my gitlab endpoint 

### ISSUE THREAD

**Issue by mipmip** [icyleaf/halite#93]
My endpoint looks like this: "https://gitlab.example.com/api/v4". Since PR "Improve resolve the URI #88" halite removes the "v4" component from my endpoint. I can fix this by adding an ending slash "https://gitlab.example.com/api/v4/" but I guest this should not have to.

**Comment by icyleaf** [comment]
Close by `0.10.8` was out.
